trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet tool install --global dotnet-dependency-check
  displayName: 'Install Dependency-Check'

- script: |
    dotnet dependency-check analyze -s $(System.DefaultWorkingDirectory)
  displayName: 'Run Dependency-Check'

- script: |
    # Parse Dependency-Check report and display results
    # Include links to solutions for each vulnerability
  displayName: 'Parse and Display Results'
