trigger:
  branches:
    exclude:
      - '*'

pr:
  branches:
    include:
      - develop

jobs:
- job: PR_Commit_Message_Check
  displayName: 'Check Commit Message Format'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      # Fetch the PR's commits
      git fetch origin refs/pull/$(Build.PullRequestId)/merge

      # Extract commit messages
      commit_messages=$(git log --format=%s refs/pull/$(Build.PullRequestId)/merge)

      # Check each commit message against the specified format
      invalid_messages=0
      for message in $commit_messages; do
        if [[ ! $message =~ ^feat\(#\d+\):.* ]]; then
          echo "Invalid commit message format: $message"
          echo "Commit message format should be: 'feat(#id): message'"
          echo "Please fix the commit message and try again."
          ((invalid_messages++))
        fi
      done

      # Fail the job if any invalid messages are found
      if [ $invalid_messages -gt 0 ]; then
        exit 1
      fi
    displayName: 'Check Commit Messages'
